### PR TITLE
Fix incorrect 1.8 item names

### LINKED ISSUE #43: java.lang.NoSuchFieldError: GOLDEN_BOOTS on Server version 1.8.9
## Installed Plugins
- LuckPerms
- CYOM

Minecraft Server Version: `CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`

## Stack Trace
```log
[18:19:29 ERROR]: Error occurred while enabling CreateYourOwnMenus v0.6.5 (Is it up to date?)
java.lang.NoSuchFieldError: GOLDEN_BOOTS
        at me.xhawk87.CreateYourOwnMenus.commands.menu.MenuGrabCommand.<clinit>(MenuGrabCommand.java:43) ~[?:?]
        at me.xhawk87.CreateYourOwnMenus.commands.MenuCommand.<init>(MenuCommand.java:60) ~[?:?]
        at me.xhawk87.CreateYourOwnMenus.CreateYourOwnMenus.onEnable(CreateYourOwnMenus.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-21fe707-741a1bd]
```
## TODO
- [x] Change `MenuGrabCommand.java:43` to correct values for 1.8.9

### PR DESCRIPTION
**Pull request by davidmvos**
- Fixes #43 

Previously, loading the Plugin on an Version before the new material ids were introduced (such as the still widely used version 1.8.9), the plugin would create a `NoSuchFieldException` for `GOLDEN_BOOTS`, `GOLDEN_LEGGINGS`, `GOLDEN_CHESTPLATE` and `GOLDEN_HELMET` aswell as `SKELETON_SKULL` and `WITHER_SKELETON_SKULL`.

The solution was to catch the `NoSuchFieldException` and then pass on the old material ids.

### CODE REVIEW

File: src/main/java/me/xhawk87/CreateYourOwnMenus/listeners/MenuListener.java [hunk 1]
```diff
@@ -93,7 +93,7 @@ public void onClickMenu(InventoryClickEvent event) {
             // First check if the clicked slot is a locked inventory slot
             int rawSlot = event.getRawSlot();
             int numInTop = event.getView().getTopInventory().getSize();
-            if ((rawSlot >= numInTop) && rawSlot != 45) { {
```
Comment (FuchsCrafter) [inline src/main/java/me/xhawk87/CreateYourOwnMenus/listeners/MenuListener.java:96]: Fixed a typo with the second brace here
